# Generated by Django 5.0.1 on 2026-09-05 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='locked', max_length=20)),
                ('last_code', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('best_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('best_lives_remaining', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='content.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Level Progress',
                'verbose_name_plural': 'User Level Progress',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'level')},
            },
        ),
        migrations.CreateModel(
            name='UserLevelSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_version', models.PositiveIntegerField()),
                ('source_code', models.TextField()),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], max_length=20)),
                ('steps_used', models.PositiveIntegerField()),
                ('lives_remaining', models.PositiveSmallIntegerField()),
                ('stars_earned', models.PositiveSmallIntegerField(default=0)),
                ('error_log', models.JSONField(default=list)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Level Submission',
                'verbose_name_plural': 'User Level Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', '-submitted_at'], name='progress_us_user_id_0ca63a_idx'), models.Index(fields=['level', '-submitted_at'], name='progress_us_level_i_a2f3f3_idx')],
            },
        ),
    ]
