# Generated by Django 5.0.1 on 2026-09-05 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic / Claude'), ('openai_compatible', 'OpenAI-compatible / Groq'), ('gemini', 'Google Gemini')], default='anthropic', max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('model', models.CharField(default='claude-opus-4-8', max_length=160)),
                ('base_url', models.URLField(blank=True, help_text='Optional provider endpoint override.')),
                ('api_key_env', models.CharField(default='ANTHROPIC_API_KEY', help_text='Environment variable name. Never paste the secret here.', max_length=120)),
                ('system_prompt', models.TextField(blank=True)),
                ('max_output_tokens', models.PositiveIntegerField(default=3000)),
                ('temperature', models.FloatField(default=0.3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI provider configuration',
                'verbose_name_plural': 'AI provider configurations',
            },
        ),
        migrations.CreateModel(
            name='GeneratedChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(default='loops', max_length=120)),
                ('difficulty', models.CharField(default='beginner', max_length=40)),
                ('prompt', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
